// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwjyvcfwiibzndgfzuwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3anl2Y2Z3aWliem5kZ2Z6dXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjcxMzQsImV4cCI6MjA2ODk0MzEzNH0.mSJh7dzzadWS0f1lCmVPjGyROe_RhPh9O7AAEh9Qvp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});